### ISSUE TITLE
Script has merge conflicts committed onto main

### ISSUE THREAD

**Issue by qwinters** [erietz/ultisnips-vscode#1]
https://github.com/erietz/ultisnips-vscode/blob/2959fc981b9e6e48b6076add5e2c32f20fded53f/scripts/ultisnips_to_vscode#L3

**Comment by qwinters** [comment]
Was about to run this (not sure how frequently these scripts are maintains), but it looks like the last commit for the `ultisnips_to_vscode` has a bunch of merge conflicts committed into it

**Comment by erietz** [comment]
Thanks for reminding me, I will fix this now!

**Comment by erietz** [comment]
Okay I believe this should be fixed now. I have tested it and it works for me. Please give it a shot and let me know if it works. Thanks for being my first customer.

**Comment by qwinters** [comment]
I'll test it out sometime today/tomorrow!
